---
# External Ansible dependencies
# Install with:
#   ansible-galaxy install -r requirements.yml -p .roles
#   ansible-galaxy collection install -r requirements.yml

roles:
  - src: git@github.com:RobertYoung/homelab-ansible-role-configure-system.git
    scm: git
    version: v1.0.0
    name: configure-system

collections:
  - name: git@github.com:RobertYoung/homelab-ansible-roles.git
    type: git
    version: v1.2.0
