---
# External Ansible dependencies
# Install with:
#   ansible-galaxy install -r requirements.yml -p .roles

roles:
  - src: git@github.com:RobertYoung/homelab-ansible-role-configure-system.git
    scm: git
    version: v1.0.1
    name: configure-system

  - src: git@github.com:RobertYoung/homelab-ansible-role-shell.git
    scm: git
    version: v1.2.0
    name: shell

  - src: git@github.com:RobertYoung/homelab-ansible-role-docker.git
    scm: git
    version: v1.0.0
    name: docker

  - src: git@github.com:RobertYoung/homelab-ansible-role-telegraf.git
    scm: git
    version: v1.0.0
    name: telegraf

  - src: git@github.com:RobertYoung/homelab-ansible-role-step-ca-client.git
    scm: git
    version: v1.2.0
    name: step-ca-client

  - src: git@github.com:RobertYoung/homelab-ansible-role-syslog.git
    scm: git
    version: v1.0.0
    name: syslog

# Note: The robertyoung.homelab collection has been replaced by standalone roles above
